### ISSUE TITLE
Implement Node.js Backend

### ISSUE THREAD

**Issue by tmichaeldb** [mindsdb/js-example#2]
See [design doc](https://docs.google.com/document/d/1Gp64VVpNdP_YulortpQ_evPtoiUEtZyXdlRe6n9dyBE/edit#heading=h.rogj89libxhm) for full context.

The web application will be served by a simple Node.js backend. It will use the JS SDK to make model predictions with preexisting models we will train using separate Node.js scripts.

**Comment by dannysheridan** [comment]
@tmichaeldb have you considered going schema-first and auto-generating the networking logic & types on the backend? our open source project supports Express if that's th server framework you've picked: www.buildwithfern.com

**Comment by tmichaeldb** [comment]
Closed by [this commit](https://github.com/mindsdb/js-example/commit/03c021d06fda89ea8b0ea9df53b9492dfcc3fe16)
